import type { Metadata } from 'next'
import './globals.css'
import NavBar from './components/NavBar'
import Header from './components/Header'
import { Noto_Sans } from "next/font/google";
import News from './components/News';
import Footer from './components/footer/Footer';

const noto_sans = Noto_Sans({
    subsets: ['latin'],
    weight: ['100','200','300','400','500','600','700','800','900']
})

export const metadata: Metadata = {
  title: 'Our Pharmacy',
  description: 'Generated by Ahmred M. Abdelnaby',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body className={noto_sans.className}>
          <Header />
          <NavBar />
          {children}
          <News />
          <Footer />
      </body>
    </html>
  )
}
